#!/bin/sh

# Set keymap
setxkbmap gb

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Set a random wallpaper
feh --bg-fill --random ~/Pictures/Wallpapers/

# Start compositor and WM
picom -b
exec bspwm
