#!/bin/bash

# Delete the folder if it exists
[ -d "/etc/X11/xorg.conf.d/" ] && sudo rm -rf /etc/X11/xorg.conf.d/

# Link xorg configs to /etc/X11/xorg.conf.d/
sudo mkdir /etc/X11/xorg.conf.d/
sudo ln $HOME/.config/xorg/70-synaptics.conf \
	/etc/X11/xorg.conf.d/70-synaptics.conf
