#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width       	 3
bspc config border_radius 		10
bspc config window_gap          45

bspc config focused_border_color "#F5E0DC"
bspc config active_border_color "#F5E0DC"
bspc config normal_border_color "#575268"
bspc config presel_border_color "#575268"

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
